<?xml version="1.0" encoding="UTF-8"?><testrun name="CalculatorProjectTest" project="JUnitProjectTest" tests="2" started="2" failures="1" errors="0" ignored="0">
  <testsuite name="io.cal.CalculatorProjectTest" time="0.045" displayname="CalculatorProjectTest" uniqueid="[engine:junit-jupiter]/[class:io.cal.CalculatorProjectTest]">
    <testcase name="add" classname="io.cal.CalculatorProjectTest" time="0.026" displayname="add()" uniqueid="[engine:junit-jupiter]/[class:io.cal.CalculatorProjectTest]/[method:add()]"/>
    <testcase name="divtest" classname="io.cal.CalculatorProjectTest" time="0.018" displayname="divtest()" uniqueid="[engine:junit-jupiter]/[class:io.cal.CalculatorProjectTest]/[method:divtest()]">
      <failure>
        <expected>class java.lang.NullPointerException</expected>
        <actual>class java.lang.ArithmeticException</actual>
        org.opentest4j.AssertionFailedError: null exception ==&gt; Unexpected exception type thrown, expected: &lt;java.lang.NullPointerException&gt; but was: &lt;java.lang.ArithmeticException&gt;&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)&#13;
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:67)&#13;
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:39)&#13;
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3153)&#13;
	at io.cal.CalculatorProjectTest.divtest(CalculatorProjectTest.java:25)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
Caused by: java.lang.ArithmeticException: / by zero&#13;
	at io.cal.CalculatorProject.div(CalculatorProject.java:18)&#13;
	at io.cal.CalculatorProjectTest.lambda$0(CalculatorProjectTest.java:25)&#13;
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:53)&#13;
	... 6 more&#13;
&#13;

      </failure>
    </testcase>
  </testsuite>
</testrun>
